# PlatformIO pre-build script (platformio.ini: extra_scripts = pre:tools/embed_web.py).
#
# Compresses web/index.html (the whole web interface: one page, vanilla JS, no external
# resource) with gzip and writes it as a PROGMEM byte array into
# src/generated/web_index.h, which src/web.cpp serves with "Content-Encoding: gzip".
# The generated header is git-ignored: web/index.html is the only source.
#
# The header is rewritten only when its content changes, so an unchanged page does not
# trigger a recompilation. The gzip stream is deterministic (no timestamp, no file name).

import gzip
import os
import sys

Import("env")  # noqa: F821 - injected by PlatformIO/SCons

project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
src_file = os.path.join(project_dir, "web", "index.html")
out_dir = os.path.join(project_dir, "src", "generated")
out_file = os.path.join(out_dir, "web_index.h")

try:
    with open(src_file, "rb") as f:
        raw = f.read()
except OSError as exc:
    sys.stderr.write("tools/embed_web.py: cannot read %s: %s\n" % (src_file, exc))
    env.Exit(1)  # noqa: F821

packed = gzip.compress(raw, compresslevel=9, mtime=0)

lines = []
for i in range(0, len(packed), 16):
    lines.append("  " + ", ".join("0x%02x" % b for b in packed[i:i + 16]))

header = (
    "// Generated by tools/embed_web.py from web/index.html. Do not edit, do not commit.\n"
    "#pragma once\n"
    "#include <Arduino.h>\n"
    "#include <pgmspace.h>\n"
    "\n"
    "// %d bytes of HTML/CSS/JS, %d bytes once gzipped.\n"
    "static const size_t WEB_INDEX_GZ_LEN = %d;\n"
    "static const uint8_t WEB_INDEX_GZ[] PROGMEM = {\n"
    "%s\n"
    "};\n"
) % (len(raw), len(packed), len(packed), ",\n".join(lines))

os.makedirs(out_dir, exist_ok=True)
try:
    with open(out_file, "r", encoding="ascii") as f:
        current = f.read()
except (OSError, UnicodeDecodeError):
    current = None

if current != header:
    with open(out_file, "w", encoding="ascii", newline="\n") as f:
        f.write(header)
    print("web/index.html -> src/generated/web_index.h (%d -> %d bytes gzip)" % (len(raw), len(packed)))
else:
    print("src/generated/web_index.h is up to date (%d bytes gzip)" % len(packed))
